[package]
name = "rusty_webservice"
version = "0.1.0"
authors = ["Pawel Rynowiecki <pawel.rynowiecki@anixe.pl>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.2", features = ["sqlite"] }
rouille = "3.0.0"
serde = "1.0.98"
serde_json = "1.0.40"
dotenv = "0.9.0"