edition = "2018"
version = "Two"

enum_discrim_align_threshold = 99
fn_args_layout = "Compressed"
format_strings = true
max_width = 169
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 99
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
